### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bugreporter34** [Kr0oked/Compass#35]
When giving permission to the sensor it still display "sensor not available" message.

![Screenshot_20230314-224805](https://user-images.githubusercontent.com/127900228/225148005-82246bfe-cb92-4259-b30b-1c03ae36ae10.png)

**Comment by Kr0oked** [comment]
Thanks for sharing this bug. There is no permission that you have to grant for the sensor. Most likely your device does not provide the necessary sensor of type TYPE_ROTATION_VECTOR that this app needs.

**Comment by Bugreporter48** [comment]
The "sensor not available" message disappears after restarting the app so I dont thing that it's the problem.

Here is a video to showcase it better what I mean.
https://user-images.githubusercontent.com/127946441/227746352-64e54ec1-fdeb-4007-a4ec-38c795bac013.mp4

**Comment by Kr0oked** [comment]
Ah now I get what you mean. I didn't even know that users can permitt access to sensors dynamically. That is not an option in my test devices. Could you tell me which android version you are using?

I just released a new version 1.10 of the app. Independently of this bug I made some changes for the error dialog. Now it contains more information and it is also dismissable. So it is possible to close the dialog and continue to use the app. I think that should solve this issue.

Thanks for taking the time to record the video!

**Comment by Bugreporter48** [comment]
> I didn't even know that users can permitt access to sensors dynamically

You can't, the reason why I can is that i'm running a custom rom on my phone that is called [GrapheneOS.](https://grapheneos.org/)

> Could you tell me which android version you are using?

Android version 13 on my Pixel 5.

> I just released a new version 1.10 of the app.

Where can I find the download link for the apk? Since I think you forgot to add one at latest [release.](https://github.com/Kr0oked/Compass/releases/tag/v1.10)

**Comment by Kr0oked** [comment]
I do not publish APKs over GitHub. The new version is already available in the Google Playstore. Otherwise you have to wait until it is also available in the FDroid store. Unfortunately FDroid needs 1-2 weeks until they build and release the new version.

**Comment by Bugreporter48** [comment]
I'm going going put this as solved after testing the latest version

**Comment by Bugreporter48** [comment]
You can close this if you like

**Comment by Kr0oked** [comment]
Alright, thanks for reporting this back!
